site_name: WgpArch Scroll Config
site_url: https://wgparch.codeberg.page/scroll/
theme:
  name: material
  palette:
    primary: light green
    accent: lime
  features:
    - navigation.tabs
    - navigation.expand
nav:
  - Home: index.md
  - Installation: installation.md
  - Keybinds: keybinds.md
  - Waybar & Scripts: waybar.md
  - Look & Feel: theming.md
  - Gallery: gallery.md
